/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.ticketwizard.presentacion;

import itson.ticketwizard.dtos.BoletoEventoDTO;
import itson.ticketwizard.dtos.BoletoEventoTransaccionDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.sql.Date;
import java.sql.Time;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dana Chavez
 */
public class BoletoUsuarioPanel extends javax.swing.JFrame {

    /**
     * Creates new form BoletosUsuarioPanel
     */
    private JPanel panelBoletos;
    
    public BoletoUsuarioPanel(){
        initComponents();
        setLocationRelativeTo(null);     
    }

    public BoletoUsuarioPanel(List<BoletoEventoTransaccionDTO> boletos) {
        initComponents();
        setLocationRelativeTo(null);
        inicializarPanelBoletos(boletos);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 11, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoappgrande.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamediana.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 310, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamediana.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamediana.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jScrollPane1.setBorder(null);
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 690, 340));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MIS BOLETOS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarPanelBoletos(List<BoletoEventoTransaccionDTO> boletos) {
        panelBoletos = new JPanel();
        panelBoletos.setLayout(new BoxLayout(panelBoletos, BoxLayout.Y_AXIS));
        panelBoletos.setBackground(new Color(36, 11, 30)); // Mantener el mismo color de fondo

        panelBoletos.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        for (BoletoEventoTransaccionDTO boleto : boletos) {
            BoletoUsuarioFormato panelBoleto = new BoletoUsuarioFormato(boleto);
            panelBoleto.setAlignmentX(Component.CENTER_ALIGNMENT); // Centrar el boleto dentro del panel
            panelBoletos.add(panelBoleto);
            panelBoletos.add(Box.createRigidArea(new Dimension(0, 10))); // Espacio entre boletos
        }

        jScrollPane1.setViewportView(panelBoletos);
        jScrollPane1.getViewport().setBackground(new Color(36, 11, 30)); // Mantener el fondo del scroll
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {

            List<BoletoEventoTransaccionDTO> boletosPrueba = List.of(
                new BoletoEventoTransaccionDTO(123456, "tipo", 1, "a","Concierto de Rock","Concierto de Rock" , "Concierto de Rock", Date.valueOf("2024-06-15"), Time.valueOf("20:00:00"), "A", 10, Date.valueOf("2024-06-15")),
                new BoletoEventoTransaccionDTO(120000, "tipo", 1, "a","Concierto de Rock","Concierto de Rock" , "Concierto de Rock", Date.valueOf("2024-06-15"), Time.valueOf("20:00:12"), "A", 10, Date.valueOf("2024-06-15")),
                new BoletoEventoTransaccionDTO(134056, "tipo", 1, "a","Concierto de Rock","Concierto de Rock" , "Concierto de Rock", Date.valueOf("2024-06-15"), Time.valueOf("20:00:00"), "A", 10, Date.valueOf("2024-06-15"))
            );

            BoletoUsuarioPanel frame = new BoletoUsuarioPanel(boletosPrueba);
            frame.setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
