/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.ticketwizard.presentacion;

import itson.ticketwizard.control.UsuarioControl;
import itson.ticketwizard.dtos.UsuarioDTO;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Dana Chavez
 */
public class RecargarSaldoPanel extends javax.swing.JFrame {
        private UsuarioControl usuarioControl;
        private int idUsuario;
        private double montoRecarga;
        private double saldoActual;

        public RecargarSaldoPanel() {
            initComponents();
            obtenerSaldoActual(); 
            actualizarSaldo();
            setLocationRelativeTo(null);
        }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        detallesSaldo = new javax.swing.JPanel();
        detallesSaldo1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        boton100 = new javax.swing.JButton();
        boton200 = new javax.swing.JButton();
        boton500 = new javax.swing.JButton();
        boton1000 = new javax.swing.JButton();
        boton2000 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 11, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoapp.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamuydelgada.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamuydelgada.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamuydelgada.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RECARGAR SALDO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Saldo Actual");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cuanto deseas recargar?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(133, 34, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(90, 14, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DETALLES DE LA ORDEN");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 110, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Confirmar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 110, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Saldo Total:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("* Compra final - No hay reembolsos");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        detallesSaldo.setBackground(new java.awt.Color(133, 34, 82));
        jPanel2.add(detallesSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, 30));

        detallesSaldo1.setBackground(new java.awt.Color(133, 34, 82));
        jPanel2.add(detallesSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 40));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Saldo a recargar:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 290, 320));

        boton100.setBackground(new java.awt.Color(36, 11, 30));
        boton100.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        boton100.setForeground(new java.awt.Color(255, 255, 255));
        boton100.setText("$100.00");
        boton100.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        boton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton100ActionPerformed(evt);
            }
        });
        jPanel1.add(boton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, 40));

        boton200.setBackground(new java.awt.Color(36, 11, 30));
        boton200.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        boton200.setForeground(new java.awt.Color(255, 255, 255));
        boton200.setText("$200.00");
        boton200.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        boton200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton200ActionPerformed(evt);
            }
        });
        jPanel1.add(boton200, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 130, 40));

        boton500.setBackground(new java.awt.Color(36, 11, 30));
        boton500.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        boton500.setForeground(new java.awt.Color(255, 255, 255));
        boton500.setText("$500.00");
        boton500.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        boton500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton500ActionPerformed(evt);
            }
        });
        jPanel1.add(boton500, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 130, 40));

        boton1000.setBackground(new java.awt.Color(36, 11, 30));
        boton1000.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        boton1000.setForeground(new java.awt.Color(255, 255, 255));
        boton1000.setText("$1000.00");
        boton1000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        boton1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1000ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 130, 40));

        boton2000.setBackground(new java.awt.Color(36, 11, 30));
        boton2000.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        boton2000.setForeground(new java.awt.Color(255, 255, 255));
        boton2000.setText("$2000.00");
        boton2000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        boton2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2000ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton100ActionPerformed
       actualizarMontoRecarga(100.0);
    }//GEN-LAST:event_boton100ActionPerformed

    private void boton200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton200ActionPerformed
        actualizarMontoRecarga(200.0);
    }//GEN-LAST:event_boton200ActionPerformed

    private void boton500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton500ActionPerformed
        actualizarMontoRecarga(500.0);
    }//GEN-LAST:event_boton500ActionPerformed

    private void boton1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1000ActionPerformed
        actualizarMontoRecarga(1000.0);
    }//GEN-LAST:event_boton1000ActionPerformed

    private void boton2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2000ActionPerformed
        actualizarMontoRecarga(2000.0);
    }//GEN-LAST:event_boton2000ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PerfilUsuarioPanel perfilUsuario = new PerfilUsuarioPanel();
        perfilUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        confirmarRecarga();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void obtenerSaldoActual() {
//            this.saldoActual = usuarioControl.obtenerSaldo(idUsuario);
        }

        private void actualizarSaldo() {
//            lblSaldoActual.setText("Saldo actual: $" + saldoActual);
        }

        private void actualizarMontoRecarga(double monto) {
            montoRecarga = monto;
            JOptionPane.showMessageDialog(this, "Monto seleccionado: $" + montoRecarga);
        }

        private void confirmarRecarga() {
            if (montoRecarga > 0) {
                usuarioControl.recargarSaldo(idUsuario, (float) montoRecarga);
                obtenerSaldoActual();  
                actualizarSaldo();  
                JOptionPane.showMessageDialog(this, "Recarga exitosa de $" + montoRecarga);
                montoRecarga = 0;
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione o ingrese un monto válido");
            }
        }
        
        private JTextField otraCantidad;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton100;
    private javax.swing.JButton boton1000;
    private javax.swing.JButton boton200;
    private javax.swing.JButton boton2000;
    private javax.swing.JButton boton500;
    private javax.swing.JPanel detallesSaldo;
    private javax.swing.JPanel detallesSaldo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
