/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.ticketwizard.presentacion;

import itson.ticketwizard.dtos.BoletoEventoTransaccionDTO;
import itson.ticketwizard.dtos.TransaccionDTO;
import itson.ticketwizard.persistencia.TransaccionDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Dana Chavez
 */
public class TransaccionPanel extends javax.swing.JFrame {
       
    private JPanel panelLista;
    private JPanel panelBoletos;
    private TransaccionDAO transaccionDAO;

    public TransaccionPanel(int idUsuario) {
        transaccionDAO = new TransaccionDAO(); 
        initComponents();
        inicializarListaTransacciones();
        inicializarPanelBoletos();
        cargarTransacciones(idUsuario);  
    }

    private void inicializarListaTransacciones() {
        panelLista = new JPanel();
        panelLista.setLayout(new BoxLayout(panelLista, BoxLayout.Y_AXIS)); 
        panelLista.setBackground(new Color(20, 20, 20));

        jScrollPane1.setViewportView(panelLista); 
    }
    
    private void inicializarPanelBoletos() {
        panelBoletos = new JPanel();
        panelBoletos.setLayout(new BoxLayout(panelBoletos, BoxLayout.Y_AXIS)); 
        panelBoletos.setBackground(new Color(36, 11, 30));

        panelBoletos.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
    }

    private void cargarTransacciones(int idUsuario) {
        List<TransaccionDTO> transacciones = transaccionDAO.obtenerTransaccionesPorUsuario(idUsuario);

        panelLista.removeAll(); 

        for (TransaccionDTO transaccion : transacciones) {
            TransaccionFormato panelTransaccion = new TransaccionFormato(transaccion);
            panelLista.add(panelTransaccion);
            panelLista.add(Box.createVerticalStrut(10));
        }

        panelLista.revalidate();
        panelLista.repaint();
    }
    
    private void cargarBoletos(List<BoletoEventoTransaccionDTO> boletos) {
        panelBoletos.removeAll(); 

        for (BoletoEventoTransaccionDTO boleto : boletos) {
            BoletoUsuarioFormato panelBoleto = new BoletoUsuarioFormato(boleto);
            panelBoleto.setAlignmentX(Component.CENTER_ALIGNMENT);
            panelBoletos.add(panelBoleto);
            panelBoletos.add(Box.createRigidArea(new Dimension(0, 10))); 
        }

        jScrollPane1.setViewportView(panelBoletos);
        jScrollPane1.getViewport().setBackground(new Color(36, 11, 30));

        panelBoletos.revalidate();
        panelBoletos.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 11, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoappgrande.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamediana.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamediana.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rayamediana.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(36, 11, 30));
        jButton1.setText("Regresar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 120, -1));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 680, 310));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        jLabel7.setText("Mis Transacciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaccionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        int idUsuario = 1; // Cambia este ID para probar con diferentes usuarios
        TransaccionPanel ventana = new TransaccionPanel(idUsuario);
        ventana.setVisible(true);

        // Simulación de boletos
        List<BoletoEventoTransaccionDTO> boletosPrueba = new ArrayList<>();
        boletosPrueba.add(new BoletoEventoTransaccionDTO(123456, "tipo", 1, "a","Concierto de Rock","Concierto de Rock" , "Concierto de Rock", Date.valueOf("2024-06-15"), Time.valueOf("20:00:00"), "A", 10, Date.valueOf("2024-06-15")));
        boletosPrueba.add(new BoletoEventoTransaccionDTO(123456, "tipo", 1, "a","Concierto de Rock","Concierto de Rock" , "Concierto de Rock", Date.valueOf("2024-06-15"), Time.valueOf("20:00:00"), "A", 10, Date.valueOf("2024-06-15")));

        ventana.cargarBoletos(boletosPrueba);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
